### ISSUE TITLE
Adding support for YAML single and double quote flow styles

### ISSUE THREAD

**Issue by andyfeller** [picotrading/jinja2-encoder-macros#4]
Part of the YAML specification describes [flow scalar styles](http://yaml.org/spec/1.2/spec.html#id2786942) options for single and double quoting that apply to block and flow keys, which isn't currently supported:
```
    {%- for key, val in item.iteritems() | sort -%}
      {%- if skip_indent and loop.first -%}
        {{ " " }}
      {%- else -%}
        {{ indent * level }}
      {%- endif -%}

      {{ key }}:
```

This prevents using the YAML macro for structures like:
```
---
foobar:
  "a b":
    "a1": 1
    "b2": false
    "c3": []
    "d4": {}
    "e5": "wtf"
    "f6": true
```
as it's currently written out as:
```
a b:
  a1: 1
  b2: false
  c3: 
  d4: 
    { } 
  e5: "wtf"
  f6: true
```

**Comment by jtyr** [comment]
Please use the [Config Encoder Filters](https://github.com/jtyr/ansible-config_encoder_filters) instead.
